env:
  es6: true
  commonjs: true
  webextensions: true
plugins:
  - no-unsanitized
extends:
  - eslint:recommended
  - plugin:no-unsanitized/DOM
rules:
  comma-dangle:
    - warn
    - always-multiline
  no-trailing-spaces: warn
  semi: warn
