env:
  es6: true
  commonjs: true
  webextensions: true
parser: "@typescript-eslint/parser"
plugins:
  - no-unsanitized
extends:
  - plugin:no-unsanitized/DOM
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
rules:
  comma-dangle:
    - warn
    - always-multiline
  no-trailing-spaces: warn
  semi: warn
  "@typescript-eslint/no-non-null-assertion": off
