name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: eslint
      run: yarn run lint:eslint

    - name: web-ext lint
      run: yarn run lint:web-ext

  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Jest tests
        run: yarn run test:coverage

      - name: Upload coverage artifacts
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage

  report:
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: test
    runs-on: ubuntu-22.04

    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage

      - name: Generate coverage badge
        run: npx make-coverage-badge --output-path ./coverage/lcov-report/badge.svg

      - name: Publish coverage report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage/lcov-report
          destination_dir: coverage
