name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: eslint
      run: yarn run lint:eslint

    - name: web-ext lint
      run: yarn run lint:web-ext

  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Jest tests
        run: yarn run test:coverage
